### PR TITLE
Fix Syntax Error

### PR DESCRIPTION
**Pull request by Im-Fran**
Fixed syntax error: 
image

### CODE REVIEW

**Comment by ndrscodes** [comment]
nice catch @Im-Fran! Which version of node are you running?

sorry for getting back to you this late.

**Comment by Im-Fran** [comment]
> nice catch @Im-Fran! Which version of node are you running?
> 
> 
> 
> sorry for getting back to you this late.

Node v16.10.0

**Comment by ndrscodes** [comment]
that's really surprising. We're using this tool in another project which regularly goes through a build pipeline (we're planning on running tests on this repo in the future as well) and it never failed on node 14.x, 16.x and 18.x... can you describe your environment a bit more?

**Comment by Im-Fran** [comment]
Here's the full log:
```log
2022-11-03T19:16:12.478409Z	Cloning repository...
2022-11-03T19:16:15.724098Z	From https://github.com/************/************
2022-11-03T19:16:15.724658Z	 * branch            3be967bec157fe98608bf04e772c7db1726f56f2 -> FETCH_HEAD
2022-11-03T19:16:15.724815Z	
2022-11-03T19:16:15.84957Z	HEAD is now at 3be967b Meta, Icons, Collections and other small things.
2022-11-03T19:16:15.850193Z	
2022-11-03T19:16:15.998631Z	
2022-11-03T19:16:16.024794Z	Success: Finished cloning repository files
2022-11-03T19:16:16.759033Z	Installing dependencies
2022-11-03T19:16:16.76956Z	Python version set to 2.7
2022-11-03T19:16:20.008544Z	v12.18.0 is already installed.
2022-11-03T19:16:21.170636Z	Now using node v12.18.0 (npm v6.14.4)
2022-11-03T19:16:21.388896Z	Started restoring cached build plugins
2022-11-03T19:16:21.404059Z	Finished restoring cached build plugins
2022-11-03T19:16:21.864024Z	Attempting ruby version 2.7.1, read from environment
2022-11-03T19:16:25.32954Z	Using ruby version 2.7.1
2022-11-03T19:16:25.682619Z	Using PHP version 5.6
2022-11-03T19:16:25.836897Z	5.2 is already installed.
2022-11-03T19:16:25.862683Z	Using Swift version 5.2
2022-11-03T19:16:25.8631Z	Started restoring cached node modules
2022-11-03T19:16:25.878841Z	Finished restoring cached node modules
2022-11-03T19:16:26.116694Z	Installing NPM modules using NPM version 6.14.4
2022-11-03T19:16:27.076278Z	npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
2022-11-03T19:16:58.934541Z	
2022-11-03T19:16:58.935013Z	> yorkie@2.0.0 install /opt/buildhome/repo/node_modules/yorkie
2022-11-03T19:16:58.935249Z	> node bin/install.js
2022-11-03T19:16:58.935391Z	
2022-11-03T19:16:59.053779Z	setting up Git hooks
2022-11-03T19:16:59.064725Z	done
2022-11-03T19:16:59.064998Z	
2022-11-03T19:16:59.156781Z	
2022-11-03T19:16:59.157152Z	> vue-demi@0.13.11 postinstall /opt/buildhome/repo/node_modules/@vueuse/shared/node_modules/vue-demi
2022-11-03T19:16:59.157331Z	> node ./scripts/postinstall.js
2022-11-03T19:16:59.157482Z	
2022-11-03T19:16:59.341551Z	
2022-11-03T19:16:59.3419Z	> core-js@3.25.5 postinstall /opt/buildhome/repo/node_modules/core-js
2022-11-03T19:16:59.342071Z	> node -e "try{require('./postinstall')}catch(e){}"
2022-11-03T19:16:59.342211Z	
2022-11-03T19:16:59.42646Z	[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
2022-11-03T19:16:59.426784Z	
2022-11-03T19:16:59.426945Z	[96mThe project needs your help! Please consider supporting of core-js:[0m
2022-11-03T19:16:59.427084Z	[96m>[94m https://opencollective.com/core-js [0m
2022-11-03T19:16:59.427223Z	[96m>[94m https://patreon.com/zloirock [0m
2022-11-03T19:16:59.42735Z	[96m>[94m bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz [0m
2022-11-03T19:16:59.427461Z	
2022-11-03T19:16:59.427569Z	[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
2022-11-03T19:16:59.427701Z	
2022-11-03T19:17:00.312233Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
2022-11-03T19:17:00.312656Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2022-11-03T19:17:00.312924Z	
2022-11-03T19:17:00.316425Z	added 1054 packages from 547 contributors and audited 1058 packages in 33.281s
2022-11-03T19:17:00.775357Z	
2022-11-03T19:17:00.77674Z	142 packages are looking for funding
2022-11-03T19:17:00.777001Z	  run `npm fund` for details
2022-11-03T19:17:00.777162Z	
2022-11-03T19:17:00.777367Z	found 1 high severity vulnerability
2022-11-03T19:17:00.77751Z	  run `npm audit fix` to fix them, or `npm audit` for details
2022-11-03T19:17:00.831959Z	NPM modules installed
2022-11-03T19:17:01.237136Z	Installing Hugo 0.54.0
2022-11-03T19:17:01.975864Z	Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
2022-11-03T19:17:01.980177Z	Started restoring cached go cache
2022-11-03T19:17:02.00015Z	Finished restoring cached go cache
2022-11-03T19:17:02.156236Z	go version go1.14.4 linux/amd64
2022-11-03T19:17:02.171472Z	go version go1.14.4 linux/amd64
2022-11-03T19:17:02.174436Z	Installing missing commands
2022-11-03T19:17:02.174924Z	Verify run directory
2022-11-03T19:17:02.175127Z	Executing user command: npm run build
2022-11-03T19:17:02.542423Z	
2022-11-03T19:17:02.542845Z	> ************@0.1.0 build /opt/buildhome/repo
2022-11-03T19:17:02.543039Z	> vue-cli-service build
2022-11-03T19:17:02.543187Z	
2022-11-03T19:17:03.534276Z	All browser targets in the browserslist configuration have supported ES module.
2022-11-03T19:17:03.534587Z	Therefore we don't build two separate bundles for differential loading.
2022-11-03T19:17:03.534737Z	
2022-11-03T19:17:03.572002Z	
2022-11-03T19:17:03.572642Z	-  Building for production...
2022-11-03T19:17:08.496543Z	
2022-11-03T19:17:08.496945Z	warn - The `purge`/`content` options have changed in Tailwind CSS v3.0.
2022-11-03T19:17:08.497134Z	warn - Update your configuration file to eliminate this warning.
2022-11-03T19:17:08.497272Z	warn - https://tailwindcss.com/docs/upgrade-guide#configure-content-sources
2022-11-03T19:17:08.688138Z	
2022-11-03T19:17:08.688474Z	[35m🌼 daisyUI components 2.33.0[0m [0m https://github.com/saadeghi/daisyui
2022-11-03T19:17:08.865821Z	  [32m✔︎ Including:[0m [0m base, components, themes[29], utilities
2022-11-03T19:17:08.866189Z	  
2022-11-03T19:17:08.866531Z	
2022-11-03T19:17:08.866709Z	warn - The `darkMode` option in your Tailwind CSS configuration is set to `false`, which now behaves the same as `media`.
2022-11-03T19:17:08.866851Z	warn - Change `darkMode` to `media` or remove it entirely.
2022-11-03T19:17:08.866999Z	warn - https://tailwindcss.com/docs/upgrade-guide#remove-dark-mode-configuration
2022-11-03T19:17:10.58855Z	[1m[33m[@vue/compiler-sfc][0m[33m ::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead.[0m
2022-11-03T19:17:10.588864Z	
2022-11-03T19:17:10.796168Z	[1m[33m[@vue/compiler-sfc][0m[33m ::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead.[0m
2022-11-03T19:17:10.796492Z	
2022-11-03T19:17:10.801156Z	[1m[33m[@vue/compiler-sfc][0m[33m ::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead.[0m
2022-11-03T19:17:10.801396Z	
2022-11-03T19:17:22.027181Z	 ERROR  Failed to compile with 1 error7:17:22 PM
2022-11-03T19:17:22.027476Z	
2022-11-03T19:17:22.027634Z	 error  in ./src/assets/half_star.svg2
2022-11-03T19:17:22.027764Z	
2022-11-03T19:17:22.027883Z	Syntax Error: /opt/buildhome/repo/node_modules/vue-svg-loader-2/index.js:33
2022-11-03T19:17:22.028259Z	  if(optimized.modernError ?? optimized.error){
2022-11-03T19:17:22.028379Z	                            ^
2022-11-03T19:17:22.028497Z	
2022-11-03T19:17:22.028607Z	SyntaxError: Unexpected token '?'
2022-11-03T19:17:22.028715Z	
2022-11-03T19:17:22.028822Z	
2022-11-03T19:17:22.028948Z	 ERROR  Error: Build failed with errors.
2022-11-03T19:17:22.029241Z	Error: Build failed with errors.
2022-11-03T19:17:22.029453Z	    at /opt/buildhome/repo/node_modules/@vue/cli-service/lib/commands/build/index.js:207:23
2022-11-03T19:17:22.029587Z	    at /opt/buildhome/repo/node_modules/webpack/lib/webpack.js:148:8
2022-11-03T19:17:22.029722Z	    at /opt/buildhome/repo/node_modules/webpack/lib/HookWebpackError.js:68:3
2022-11-03T19:17:22.029867Z	    at Hook.eval [as callAsync] (eval at create (/opt/buildhome/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
2022-11-03T19:17:22.030006Z	    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/opt/buildhome/repo/node_modules/tapable/lib/Hook.js:18:14)
2022-11-03T19:17:22.030133Z	    at Cache.shutdown (/opt/buildhome/repo/node_modules/webpack/lib/Cache.js:150:23)
2022-11-03T19:17:22.030245Z	    at /opt/buildhome/repo/node_modules/webpack/lib/Compiler.js:1225:15
2022-11-03T19:17:22.030361Z	    at Hook.eval [as callAsync] (eval at create (/opt/buildhome/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
2022-11-03T19:17:22.030472Z	    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/opt/buildhome/repo/node_modules/tapable/lib/Hook.js:18:14)
2022-11-03T19:17:22.030864Z	    at Compiler.close (/opt/buildhome/repo/node_modules/webpack/lib/Compiler.js:1218:23)
2022-11-03T19:17:22.031028Z	    at /opt/buildhome/repo/node_modules/webpack/lib/webpack.js:147:16
2022-11-03T19:17:22.031165Z	    at finalCallback (/opt/buildhome/repo/node_modules/webpack/lib/Compiler.js:441:32)
2022-11-03T19:17:22.031283Z	    at /opt/buildhome/repo/node_modules/webpack/lib/Compiler.js:458:13
2022-11-03T19:17:22.031394Z	    at Hook.eval [as callAsync] (eval at create (/opt/buildhome/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
2022-11-03T19:17:22.03151Z	    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/opt/buildhome/repo/node_modules/tapable/lib/Hook.js:18:14)
2022-11-03T19:17:22.031627Z	    at onCompiled (/opt/buildhome/repo/node_modules/webpack/lib/Compiler.js:456:21)
2022-11-03T19:17:22.031744Z	    at /opt/buildhome/repo/node_modules/webpack/lib/Compiler.js:1196:17
2022-11-03T19:17:22.031865Z	    at Hook.eval [as callAsync] (eval at create (/opt/buildhome/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
2022-11-03T19:17:22.03201Z	    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/opt/buildhome/repo/node_modules/tapable/lib/Hook.js:18:14)
2022-11-03T19:17:22.032138Z	    at /opt/buildhome/repo/node_modules/webpack/lib/Compiler.js:1192:33
2022-11-03T19:17:22.032255Z	    at finalCallback (/opt/buildhome/repo/node_modules/webpack/lib/Compilation.js:2787:11)
2022-11-03T19:17:22.032368Z	    at /opt/buildhome/repo/node_modules/webpack/lib/Compilation.js:3092:11
2022-11-03T19:17:22.032477Z	    at Hook.eval [as callAsync] (eval at create (/opt/buildhome/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
2022-11-03T19:17:22.032583Z	    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/opt/buildhome/repo/node_modules/tapable/lib/Hook.js:18:14)
2022-11-03T19:17:22.032704Z	    at /opt/buildhome/repo/node_modules/webpack/lib/Compilation.js:3085:38
2022-11-03T19:17:22.032813Z	    at eval (eval at create (/opt/buildhome/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
2022-11-03T19:17:22.032941Z	    at eval (eval at create (/opt/buildhome/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
2022-11-03T19:17:22.033058Z	    at runMicrotasks (<anonymous>)
2022-11-03T19:17:22.03354Z	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2022-11-03T19:17:22.05771Z	npm ERR! code ELIFECYCLE
2022-11-03T19:17:22.058219Z	npm ERR! errno 1
2022-11-03T19:17:22.058617Z	npm ERR! ************@0.1.0 build: `vue-cli-service build`
2022-11-03T19:17:22.058803Z	npm ERR! Exit status 1
2022-11-03T19:17:22.058947Z	npm ERR! 
2022-11-03T19:17:22.059246Z	npm ERR! Failed at the ************@0.1.0 build script.
2022-11-03T19:17:22.059373Z	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2022-11-03T19:17:22.071477Z	
2022-11-03T19:17:22.071882Z	npm ERR! A complete log of this run can be found in:
2022-11-03T19:17:22.072086Z	npm ERR!     /opt/buildhome/.npm/_logs/2022-11-03T19_17_22_059Z-debug.log
2022-11-03T19:17:22.080202Z	Failed: build command exited with code: 1
2022-11-03T19:17:23.096063Z	Failed: an internal error occurred
```

I've redacted the name of the repo and url.

And this is the svg:
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
<path fill-rule="evenodd" d="M9.9,0c-0.5,0-1,0.3-1.2,0.8v0l-2.1,5L1.2,6.2C0,6.3-0.4,7.8,0.5,8.6l4.1,3.5
	l-1.3,5.3c-0.3,1.1,1,2,2,1.4L9.9,16V0z"/>
	</svg>
```

**Comment by ndrscodes** [comment]
At the top of your log file, it says you're running Node.js version (see `Now using node v12.18.0 (npm v6.14.4)`). Node 12.x reached end-of-life in April 2022, so i recommend you update. As your fix doesn't negatively affect newer versions of Node, we are going to merge this. However, we are explicitly not going to support EOL versions of node, so you might still run into trouble in the future.

**Review by ndrscodes — APPROVED** [review]

**Comment by Im-Fran** [comment]
> At the top of your log file, it says you're running Node.js version (see `Now using node v12.18.0 (npm v6.14.4)`). Node 12.x reached end-of-life in April 2022, so i recommend you update. As your fix doesn't negatively affect newer versions of Node, we are going to merge this. However, we are explicitly not going to support EOL versions of node, so you might still run into trouble in the future.

Lol, maybe I added a wrong argument to cloudflare pages xD. Thanks for noticing

**Pull request merged**
