### PR TITLE
Fix SVGO config setup

### LINKED ISSUE #45: Config svgo override doesn't work
I'm using vue-cli and added vue-svg-loader-2 to my webpack config:
```
    svgRule
      .use('vue-loader')
      .loader('vue-loader')
      .end()
      .use('vue-svg-loader-2')
      .loader('vue-svg-loader-2')
      .options({
        svgo: {
          plugins: [
            {
              name: 'preset-default',
              params: {
                overrides: {
                  cleanupIds: false,
                  collapseGroups: false,
                  inlineStyles: {
                    onlyMatchedOnce: false,
                  },
                },
              },
            },
          ],
        },
      })
      .end();
```

However the config is not overridden. Instead the default config in vue-svg-loader-2 is used.

The following patch solves this issue for me:
```
diff --git a/node_modules/vue-svg-loader-2/index.js b/node_modules/vue-svg-loader-2/index.js
index 23304af..7c4f593 100644
--- a/node_modules/vue-svg-loader-2/index.js
+++ b/node_modules/vue-svg-loader-2/index.js
@@ -22,7 +22,7 @@ module.exports = function vueSvgLoader(svg) {
   let { svgo: svgoConfig } = this.getOptions() || {};
 
   // merge svgoConfig with defaultConfig in order to force inlining <style> tags
-  svgoConfig = {...svgoConfig, ...defaultConfig};
+  svgoConfig = {...defaultConfig, ...svgoConfig};
 
   let optimized;
   optimized = optimize(svg, {
```

### PR DESCRIPTION
**Pull request by ndrscodes**
correctly builds a valid SVGO config from the `svgo` config passed via webpack options. This fixes #45 and #25.

### CODE REVIEW

**Comment by ndrscodes** [comment]
licence checks are still failing because of a missing rebase afaik. you can check the current state on FOSSA, this PR right here doesn't cause the issue and should thus be merged :)

**Review by kwilfert — APPROVED** [review]
This merge would have my approval. The changes in code seem sensible, and all tests succeed.

**Comment by msokk** [comment]
@ndrscodes Will there be a new beta release soon? 🙏

**Comment by ndrscodes** [comment]
Definitely! Just waiting for PR #42 to go through! Beta 5 should be available by the end of the day (UTC, that is)!

**Comment by ndrscodes** [comment]
@msokk 0.17.0-beta.5 is now available! :)

**Pull request merged**
