### PR TITLE
feat: implement test suite

### PR DESCRIPTION
**Pull request by ndrscodes**
adds unit tests.
tests added:
- Uses a custom webpack compiler in order to check if a valid template is created
- Uses a custom webpack compiler in order to test if `vue-loader` is able to compile the template generated by the loader
- checks if the loader yields the same result when invoked by webpack and when called directly
- checks if the loader injects a `v-on` directive into the svg tag if Vue 2 is detected

### CODE REVIEW

**Comment by kwilfert** [comment]
These tests are a very nice addition to the repo.
They run fine and pass.

**Review by kwilfert — DISMISSED** [review]

**Comment by ndrscodes** [comment]
sorry for all the trouble. Turns out that vue-loader and compiler-sfc are conflicting on node 14. had to remove the check in order to ensure templates can be rendered on vue 3 too.

**Review by kwilfert — DISMISSED** [review]
Tests run and succeed.
No vulnerabilities.
Has my approval as long as the conflicts are resolved


Sorry for the immense delay. It completely slipped my mind during the development for my bachelor thesis

**Review by Bachenbenno — DISMISSED** [review]
Tests were successful as well.

Only vulnerability found was in loader-utils, so none concerning this PR.

Has my approval too.

**Review by kwilfert — APPROVED** [review]
All tests succeeded, no vulnerabilities, no errors.

**Review by Bachenbenno — APPROVED** [review]
All tests successful and no more vulnerabilities found, looks good

**Pull request merged**
